### ISSUE TITLE
[Bug]: One string cannot probably be translated

### ISSUE THREAD

**Issue by CyrilleB79** [nvdaes/readFeeds#18]
### Summary

Found an f-string during translation

### To reproduce

The following string was found in the translatable strings:
> Feeds: {addressFile} ({getActiveProfile()})
This string is coming from an f-string in the code.

I think that gettext does not allow (yet) to use f-strings. At least it was the case in NVDA core Python 3.7.

I have not tested myself however on the add-on. But I expect it to be an issue when translating in French since "Feed" is translated to "Flux".
I have had a look at the Spanish (up-to-date) translation, but the English word "feed" seems to be used in Spanish as well.

### Expected behavior

Could you test and check it?
If it is confirmed that f-strings are not allowed, you should replace it by a `.format()` pattern.

### Version

11.1

**Comment by nvdaes** [comment]
Thanks, I"ll look at this in the next weekend or before.

Enviado desde mi iPhone

**Comment by nvdaes** [comment]
Fixed in #19

**Comment by CyrilleB79** [comment]
The issue is still present today as explained in #37.
Sorry, I had not reviewed #19 before nor after it was merged.

I have submitted #37 to fix it.
